---

- name: Install Zookeeper
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - openjdk-7-jre-headless
    - "zookeeper={{ zookeeper.version }}*"
    - "zookeeperd={{ zookeeper.version }}*"
